# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "reference_data"
description: Get the reference data (PCGR and VEP cache) required for variant annotation and prioritization
keywords:
  - vcf
  - pcgr
  - reference
  - cache
components:
  - pcgr/getref
  - untar
input:
  - genome:
      type: string
      description: The reference genome
      enum:
        - GRCh38
        - GRCh37
  - pcgr_download:
      type: boolean
      description: Whether to download the PCGR reference (true) or use a local PCGR database (false)
  - pcgr_bundleversion:
      type: string
      description: PCGR version to download
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  - pcgr_database_dir:
      type: string
      description: Path to a local PCGR database directory (used when pcgr_download is false)
  - vep_cache:
      type: string
      description: Path or cloud URL to the VEP cache base directory
  - vep_cache_version:
      type: string
      description: VEP cache version to download
      pattern: "^[0-9]+$"
  - vep_species:
      type: string
      description: Species for VEP cache

output:
  - pcgr_dir:
      type: file
      description: |
        Channel containing PCGR reference directories.
        Structure: [ path(pcgr_dir) ]
      pattern: "*"
  - vep_cache:
      type: file
      description: |
        Channel containing VEP cache directories.
        Structure: [ path(vep_cache) ]
      pattern: "*"
authors:
  - "@famosab"
maintainers:
  - "@famosab"
